version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/circle-ci-test
    steps:
      - checkout
      - run: pwd
      - run: cat package.json
      - run: ls
      - run: npm install
      - run: npm test
      - run: node --version
      - run: serverless --version

