version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.10.1
    working_directory: ~/circle-ci-test
    steps:
      - checkout
      - run: pwd
      - run: cat package.json
      - run: npm install
      - run: node --version
      - run: serverless --version

